/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "inverse-on-surface": "#f0f1f3",
        "on-surface": "#191c1e",
        "primary-fixed": "#dbe1ff",
        "secondary-fixed": "#ffddb8",
        "primary": "#004ac6",
        "surface-container": "#edeef0",
        "outline-variant": "#c3c6d7",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "tertiary-container": "#5069bb",
        "on-tertiary-fixed": "#00164e",
        "surface-container-highest": "#e1e2e4",
        "on-secondary-fixed-variant": "#653e00",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "on-background": "#191c1e",
        "surface-tint": "#0053db",
        "on-tertiary-container": "#eff0ff",
        "surface-container-low": "#f3f4f6",
        "tertiary-fixed-dim": "#b6c4ff",
        "surface-container-high": "#e7e8ea",
        "on-tertiary-fixed-variant": "#264191",
        "on-primary-fixed": "#00174b",
        "primary-container": "#2563eb",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fb",
        "tertiary": "#3750a0",
        "on-surface-variant": "#434655",
        "inverse-primary": "#b4c5ff",
        "on-secondary-fixed": "#2a1700",
        "tertiary-fixed": "#dce1ff",
        "secondary": "#855300",
        "on-secondary": "#ffffff",
        "outline": "#737686",
        "surface": "#f8f9fb",
        "error": "#ba1a1a",
        "background": "#f8f9fb",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fea619",
        "on-primary-container": "#eeefff",
        "surface-variant": "#e1e2e4",
        "surface-dim": "#d9dadc",
        "secondary-fixed-dim": "#ffb95f",
        "inverse-surface": "#2e3132",
        "on-secondary-container": "#684000"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-margin": "32px",
        "gutter": "24px",
        "stack-md": "16px",
        "section-gap": "48px",
        "stack-lg": "24px",
        "stack-sm": "8px"
      },
      "fontFamily": {
        "headline-sm": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "body-sm": ["Manrope"],
        "label-md": ["Manrope"],
        "headline-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "label-sm": ["Manrope"],
        "sans": ["Manrope", "sans-serif"]
      },
      "fontSize": {
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "0", "fontWeight": "600" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}
